### PR TITLE
[sp/metadata] add Organization

### LINKED ISSUE #10: Mancanza struttura Organization
Buongiorno, 

nella libreria non è presente il supporto al metadata Organization (ora obbligatorio) per spid.

Sarebbe possibile aggiungere questa funzionalità ?

Grazie,
Nicolas.

### PR DESCRIPTION
**Pull request by ezatti**
Add Organization object which is required in the SP metadata accordingly to [spid documentation](https://docs.italia.it/italia/spid/spid-regole-tecniche/it/stabile/metadata.html#service-provider).

Closes #10

### CODE REVIEW

**Review by peppelinux — APPROVED** [review]

**Comment by peppelinux** [comment]
Hi @ezatti 

can you fix the conflicts?
I'd like to merge your contribution

**Review by peppelinux — CHANGES_REQUESTED** [review]
We need to fix che conflictings files

**Comment by ezatti** [comment]
Hi @peppelinux,
I fixed the conflicts

**Review by yaronius — APPROVED** [review]
I would also like this to be merged! 👍

**Pull request merged**
